vars/runTest.groovy, vars/sconsBuild.groovy
Re-push of #6 since #6 was based on another PR and merged to that PR.  I need to pay more attention next time.
Code reviews for this are in #6.
=> Hack to get sconsBuild to return rc

vars/checkPatch.groovy
* Add groovydoc
* Require env.DAOS_JENKINS_NOTIFY_STATUS for an actual update.
* Lookup the credentials for the GITHUB upddate instead of having
them passed.
* Provide a default empty Map as a parameter.
=> CORCI-502 checkPatch Groovy only for Production

vars/sconsBuild.groovy
When cleaning, also remove the scons Variables() file.
=> Remove scons configuration options cache file

vars/checkPatch.groovy, vars/provisionNodes.groovy
* Add provisionNodes step.
Allows snapshot option for VMs, and a power cycle only option.
By default waits for the provisioning or power cycle to complete.
* Update checkPatch step credential ID.
=> CORCI-445 Adding node provisioning

vars/runTest.groovy
vars/runTest.groovy got missed in 509e853.
=> CORCI-531 Fix pipeline-lib vars/ for local variables

vars/runTest.groovy
=> Use error to signal a failure in runTest

vars/provisionNodes.groovy
=> Need golang bin

vars/checkPatch.groovy
The code review repository should be in GitHub, move it there and update
pipeline-lib to use it.
=> CORCI-591 Switch code review to GitHub

src/com/intel/cancelPreviousBuildsInternal.groovy, vars/cancelPreviousBuilds.groovy
A function to cancel old builds of the currently running job.
=> CORCI-607 Cancel old builds

src/com/intel/doGetHttpRequest.groovy, vars/checkPatch.groovy, vars/runTest.groovy, vars/sconsBuild.groovy, vars/stepResult.groovy
=> CORCI-522 Provide a link directly to a failing step's log

vars/sconsBuild.groovy
This can be used for builds that want to analyse the build
output after building.
=> Add sconsBuild option to tee output to a file

vars/provisionNodes.groovy
This reverts commit 3d7ab780d9dea19adfde576b8eb931202fc132e9.
Causing hpc-ior to fail to install.
=> Revert "DAOS-2240 Add Jenkins RPM project repos to provisioned nodes (#32)"

vars/archiveArtifacts.groovy, vars/githubNotify.groovy, vars/junit.groovy, vars/provisionNodes.groovy, vars/publishValgrind.groovy, vars/runTest.groovy, vars/stepResult.groovy
A staging system is to verify CI environment changes, and does not need
to do full CI tests.
stepResult.groovy should only report to Github results from production
Jenkins systems.
Adding wrappers for archiveArtifacts, githubNotify, junit, publishValgrind.
=> CORCI-623 Inhibit tests for staging systems.

vars/provisionNodes.groovy
So that it can be reported to the caller and the caller can exit
accordingly.
=> CORCI-673 Get pdsh's exit status

vars/provisionNodes.groovy
Move the provisioning script repository from Gerrit.
=> corci ci: Move repo from gerrit

vars/provisionNodes.groovy
So that we can test the the build RPMs.
=> DAOS-2240 Support SLES12SP3 post-provision configuration

vars/provisionNodes.groovy
=> CORCI-686 build: Fix provisionNode el7 default

vars/provisionNodes.groovy
=> CORCI-687 build: provisionNodes ignore hostkeys

vars/provisionNodes.groovy
Signed-off-by: Samir <samir.raval@intel.com>
=> DAOS-1316 Test: Adding clustershell python package for running control plane command in cluster.

Jenkinsfile, vars/provisionNodes.groovy
Add artifact repository support to provsionNodes.
=> CORCI-749 build: Add Artifact repository support

Jenkinsfile, vars/provisionNodes.groovy
Convert to new repository format to separate group repositories from
local repositories.
=> CORCI-768 build: Convert to new repository format

vars/runTest.groovy
Reverts daos-stack/pipeline-lib#60
=> Revert "Don't try to grep missing files"

Jenkinsfile, vars/packageBuildingPipeline.groovy
=> Artifact specs cannot be empty

vars/packageBuildingPipeline.groovy
Also add Quick-build: pragma support.
=> Add a test stage

vars/packageBuildingPipeline.groovy
To specify which packaging/ repo branch to check against.
=> Add a packaging/ repo branch pragma

vars/packageBuildingPipeline.groovy
Update vars/packageBuildingPipeline.groovy to build Ubuntu packages in
a chroot environment.
=> CORCI-783 build: Ubuntu packaging with chroot

vars/packageBuildingPipeline.groovy
=> Use make_args in all stages 

vars/sconsBuild.groovy
Need to use scons-3, for instance on some platforms
=> DAOS-3268 build: Add scons_exe variable so alternative can be used

vars/provisionNodes.groovy
Not just previous incarnations of repos we want to add.
This is a poor man's node-reuse (rather than reprovision).
=> Erase all previously installed jenkins repos

vars/packageBuildingPipelineDAOS.groovy
That builds DAOS with the package being updated as a test against the
packge being updated.
=> Add a packageBuildingPipeline variant for DAOS

vars/packageBuildingPipelineDAOS.groovy
Add a CentOS 8 Stage needed for building SLURM.
=> DCO-8741 build: Add CentOS 8 stage

vars/provisionNodes.groovy
Need two sync commands to ensure that a sync is done.
=> DCO-8890 build: Need two sync commands.

vars/commitPragma.groovy, vars/packageBuildingPipelineDAOS.groovy
Using the pragma "DAOS-test-branch".
=> Allow providing DAOS test branch via commit

vars/sconsBuild.groovy
Add coverity support to sconsBuild
=> CORCI-750 build: Add coverity to sconsBuild

vars/provisionNodes.groovy
To developers when trying to clean up pre-existing server.log.
=> CORCI-826 build: Provide error message

Jenkinsfile, vars/provisionNodes.groovy
Make sure /tmp/daos.log and /tmp/server.log are deleted during
provisionNodes.
=> CORCI-826 build: Clean out /tmp/daos.log

vars/provisionNodes.groovy
In /root/last_run-env.txt for previous-run-failure post-mortem.
=> Stash run environent

Jenkinsfile, vars/provisionNodes.groovy
Add removal of more files left over from testing.
Do not fail if unable to remove files before rebooting.  Only fail
if files can not be removed after a reboot.
=> CORCI-826 build: More CI node cleanup.

vars/provisionNodes.groovy
Wait for nodes to be ready after a reboot before checking to
see if log files still need to be removed.
=> CORCI-826 build: Fix check after reboot

vars/publishToRepository.groovy
=> Only publish from the defined publishing branch

vars/packageBuildingPipeline.groovy, vars/packageBuildingPipelineDAOS.groovy
=> Package building project can define a publishing branch

vars/coverityToolDownload.groovy, vars/packageBuildingPipelineDAOS.groovy, vars/sconsBuild.groovy
Add coverityToolDownload as a separate step.
Add an optional Coverity buiding step to packageBuildingPipelineDAOS
=> CORCI-752 build Coverity scan updates

vars/packageBuildingPipeline.groovy
In add_archiving_cmds to allow per distro commands.
=> Replace <distro> with distro nickname

Jenkinsfile
=> CORCI-768 build: Use master branch of pipeline-lib

vars/sconsBuild.groovy
The option has never really worked well
=> CART-89 build: Remove --update-prereq option from scons

vars/provisionNodes.groovy
=> Add /var/tmp/daos_testing to cleanup

vars/provisionNodes.groovy
=> Escape / in URLs

vars/provisionNodes.groovy
Since a previous change changed a / to a %252 in the URL for an added
repo.
=> Change / -> %252 in pathname from URL

vars/provisionNodes.groovy
=> Yum has issues with repos with % in the name

vars/provisionNodes.groovy
If the new name is the same as the old name.
=> Don't try to rename a file

Jenkinsfile, vars/provisionNodes.groovy, vars/runTest.groovy
Otherwise it returns an error and confuses the result with grep not
finding any matches.
=> Don't grep non-existent file patterns

Jenkinsfile
=> Add release/0.9 and master provisioning tests

Jenkinsfile, vars/provisionNodes.groovy
Change to default to always doing snapshot restores.
=> CORCI-854 build: Support Snapshot restores.

vars/provisionNodes.groovy
=> Handle return from provisionNodesSystem

vars/publishToRepository.groovy
=> Only publish on landing to known release branches

vars/publishToRepository.groovy
=> Fix syntax error introduced in previous commit

vars/packageBuildingPipeline.groovy, vars/packageBuildingPipelineDAOS.groovy
Just to make sure anyone adding it understand the ramifications.
=> Add a warning about adding buildDiscarder()

vars/packageBuildingPipeline.groovy
=> Fix collection of config.log

vars/commitPragma.groovy
=> .trim() whitespace off of commit  pragmas

vars/runTest.groovy, vars/runTestFunctional.groovy, vars/sconsBuild.groovy
=> Add a runTestFunctional step

vars/runTestFunctional.groovy
To make sure that we are testing from the RPM installed files.
=> Remove the install/ dir for RPM testing

vars/sconsBuild.groovy
In order to test multiple build types, we don't want to
rebuild everything so enable ability to skip clean step
=> DAOS-623 build: Add ability to bypass clean

vars/sconsBuild.groovy
=> DAOS-623 build: Remove scons database in clean step

vars/sconsBuild.groovy
=> Enable parallel builds in sconsBuild()

vars/sconsBuild.groovy
=> Define scons_args in outer scope

vars/publishToRepository.groovy
=> Fix extraneous }

Jenkinsfile
=> CORCI-918 build: set library to master

vars/buildRpm.groovy, vars/buildRpmPost.groovy, vars/junit.groovy, vars/parseStageInfo.groovy, vars/provisionNodes.groovy, vars/publishToRepository.groovy, vars/pythonBanditCheck.groovy, vars/runTest.groovy, vars/stepResult.groovy, vars/testRpm.groovy
buildRpm: All the steps to build an RPM in one step.
buildRpmPost: Universal post step for RPM.
=> CORCI-918 Build: Refactor RPM build steps

vars/buildRpmPost.groovy, vars/coverityPost.groovy, vars/functionalTest.groovy, vars/functionalTestPost.groovy, vars/parseStageInfo.groovy, vars/provisionNodes.groovy, vars/runTest.groovy, vars/runTestFunctional.groovy, vars/scanRpms.groovy, vars/sconsBuild.groovy, vars/unitTest.groovy, vars/unitTestPost.groovy
runTestFunctional: Document parameters passsed through to runTest.
sconsBuild: Add coverity file cleanup.
parseStageInfo: Add parsing of additional stage info.
coverityPost: Post processing for sconsBuild of Coverity.
functionalTest: Common step for all Functional tests.
functionalTestPost: Common post step for all Functional tests.
scanRpms: Step to scan installed RPMs with virus scanner.
unitTest: Common step for all Unit tests including Bullseye.
unitTestPost: Common post step for all Unit tests including Bullseye.
=> CORCI-918 build: Add more test/post steps

vars/provisionNodes.groovy, vars/provisionNodesV1.groovy
Add support for provisioning Leap 15.
Reduce complexity by un-inlining scriptlets.
=> Support Leap 15

vars/coverityPost.groovy, vars/functionalTest.groovy, vars/parseStageInfo.groovy, vars/unitTest.groovy
Fix parameter names and default usages for new routines to be deployed.
=> CORCI-918 build: Bugfixes fixes.

vars/runTestFunctional.groovy, vars/runTestFunctionalV1.groovy, vars/testRpm.groovy
=> Move Functional inline scripts to DAOS project

.github/workflows/update_pipeline_lib_branch.yml, Jenkinsfile
=> Fix pipeline-lib Library branch

Jenkinsfile, vars/packageBuildingPipeline.groovy, vars/packageBuildingPipelineDAOS.groovy
=> Update Leap 15 package build to 15.2

vars/dockerBuildArgs.groovy, vars/packageBuildingPipeline.groovy, vars/packageBuildingPipelineDAOS.groovy, vars/parseStageInfo.groovy, vars/provisionNodes.groovy, vars/scanRpms.groovy
Update Leap 15 build to 15.2 and Ubuntu to 20.04.
=> Update Leap 15 and Ubuntu build versions

vars/functionalTestPost.groovy
Add log_size_check.xml file to results to be reported.
Signed-off-by: Justiniano-pagn <amanda.justiniano-pagn@intel.com>
=> DAOS-5342 test: add new results.xml path file to report big files

Jenkinsfile, vars/runTest.groovy
runTest.groovy should mark a stage as failed when it detects
a script failure.
=> CORCI-1001 build: Signal runTest failures

vars/parseStageInfo.groovy, vars/unitTestPost.groovy
Add support for NLT jobs, and make the calling of recordIssues optional in unitTestPost.
The logic is slightly complicated by the requirement to be backwards compatible.
=> CORCI-1010 test: Add support for dedicated NLT stage.

vars/packageBuildingPipeline.groovy, vars/packageBuildingPipelineDAOS.groovy
Specifically with spectool since it can be silent about it's issues.
=> Add a stage to sanity check the specfile

vars/packageBuildingPipeline.groovy, vars/packageBuildingPipelineDAOS.groovy
=> Need to use make_args in show_sources check

Jenkinsfile, vars/parseStageInfo.groovy, vars/provisionNodes.groovy
Update for CentOS 7.9 testing.
Fix up future CentOS 8 testing.
Fix up setting Java version.
=> CORCI-1013 Build: Update for Centos7.9 testing

vars/parseStageInfo.groovy
=> Set Avocado tag based on PR vs. timer

Jenkinsfile, vars/stepResult.groovy
Instead of polluting PRs with comments.
=> Email build status directly

vars/parseStageInfo.groovy
By adding any space separated list of features as avocado tags.
=> Add support for Features commit pragma

vars/stepResult.groovy
=> Add PR name to e-mailed stage report

vars/runTestFunctional.groovy
=> Quote passed environment

vars/dockerBuildArgs.groovy, vars/stepResult.groovy
Also extend dockerBuildArgs() to do some steps optionally, defaulting to
existing behaviour.
=> Add stage name to e-mail subject

vars/dockerBuildArgs.groovy
=> Booleans in Groovy are not upper-case first letter

vars/parseStageInfo.groovy
Since there are known failures in that set.
=> DAOS-6468 ci: Disable full_regression for Features:

vars/parseStageInfo.groovy
=> Splitting "" doesn't yield an empty list

vars/unitTestPost.groovy
https://github.com/jenkinsci/warnings-ng-plugin/blob/master/doc/Documentation.md#configure-the-selection-of-the-reference-build-baseline
=> Update to warningsplug 8.5.0

vars/unitTestPost.groovy
=> CORCI-1039: nlt: Set the reference repo correctly.

vars/functionalTestPost.groovy, vars/runTestFunctional.groovy, vars/runTestFunctionalV1.groovy
=> DAOS-6274 test: Restructure DAOS logs

vars/dockerBuildArgs.groovy, vars/sconsBuild.groovy
The logic for cachebust and add_repos was wrong in that they defaulted
to true, and could only be set to true.
Update they logic so they can also be set to false.
=> DAOS-6742: build: Update dockerBuildArgs to handle false correctly.

Jenkinsfile, vars/dockerBuildArgs.groovy
To ensure that base images are up-to-date.
=> Add --pull to docker build args

Jenkinsfile, vars/dockerBuildArgs.groovy
Reverts daos-stack/pipeline-lib#197
Jenkins is not using Nexus as it's configured to.
=> Revert "Add --pull to docker build args"

Jenkinsfile, vars/parseStageInfo.groovy
It might have been a bit too clever and not being run in the order that
was intended resulting in the Avocado tags not being set as expected.
Also add support for Test-tag: as a job parameter to help with weekly
testing job maintenance.
=> CORCI-1058 test: Simplify the test tag logic

vars/dockerBuildArgs.groovy, vars/parseStageInfo.groovy, vars/provisionNodesV1.groovy
Support additional repositories for Dockerfiles.
DAOS_STACK_distro_ver_type_REPO where:
distro is oneof CENTOS LEAP or UBUNTU
ver is the major version of the distro
type is one of "LOCAL", "STABLE", "RELEASE", "DEV"
LOCAL is only the locally built artifacts
STABLE is local artifacts + Proxied distro repositories
RELEASE is release artifacts + Proxied distro repositories
DEV is for testing new repositories.
Only pass the repository definitions that the dockerfile can
use.
=> CORCI-1063 build: Support docker images repos

vars/dockerBuildArgs.groovy
The Docker distros are now only for externally maintained signed
packages
The DAOS repos are for any locally build artifacts and will probably not be
officially signed.
=> CORCI-1063 Build: Docker distro and DAOS repos

vars/skipStage.groovy
Add stage "Build on CentOS 7 with Clang debug"
Signed-off-by: Dalton Bohning <daltonx.bohning@intel.com>
=> DAOS-7284: add centos7  clang  debug

vars/provisionNodes.groovy, vars/skipStage.groovy
Mainly just as a Vagrant host for now.
=> Add initial support for Fedora

vars/skipStage.groovy, vars/testsInStage.groovy
tests_in_stage() was moved to it's own variable.
=> Fix syntax error and remove dead code

vars/parseStageInfo.groovy
Expand release branch PR testing to include daily_regression
=> DAOS-7817 test: Expand release branch PR testlist

vars/unitPackages.groovy
Fix issue where Unit Test Bullseye stage failed looking for
mercury rpm in pre-test
=> DAOS-8337 test: Fix UT Bullseye

vars/parseStageInfo.groovy, vars/skipStage.groovy
Adding support for building multiple dot releases.
=> CORCI-1103 Build: Update for CentOS 8.4, Leap 15.3

vars/skipStage.groovy
=> DAOS-8346 test: Add the Fault injection testing stage.

Jenkinsfile, vars/functionalTest.groovy, vars/functionalTestPostV2.groovy, vars/skipStage.groovy, vars/valgrindReportPublish.groovy
Also DRY out RPM scanning skip determination.
=> Submit test data to Launchable

vars/hwDistroTarget.groovy, vars/parseStageInfo.groovy, vars/skipStage.groovy
=> Allow distro targets to be overridable

vars/parseStageInfo.groovy
This is due to our lacking group repos at the moment as proxy repos are
created with their major and minor value.
=> DAOS-8915 build: Default Leap version to 15.3

vars/hwDistroTarget2.groovy
Reverts daos-stack/pipeline-lib#250
It seems to have problems with Mellanox OFED.
=> Revert "Run EL8 testing on hardware nodes"

vars/functionalPackages.groovy, vars/getDAOSPackages.groovy
To be added to the list of versioned daos packages to install.
=> Allow caller to specify some additional daos packages

vars/releaseCandidate.groovy
To match with - in front of 'rc'.
=> Fix release candidate detection

vars/skipStage.groovy
=> CORCI-1148 ci: Skip Coverity stage

vars/dockerBuildArgs.groovy, vars/sconsBuild.groovy, vars/skipStage.groovy
=> CART-89 build: Add a skip-pragma for CentOS 7 builds.

vars/dockerBuildArgs.groovy, vars/sconsBuild.groovy, vars/skipStage.groovy
Reverts daos-stack/pipeline-lib#281
=> Revert "CART-89 build: Add a skip-pragma for CentOS 7 builds."

vars/parseStageInfo.groovy
Reverts daos-stack/pipeline-lib#294
=> Revert "DAOS-9562 test: Support VMD clusters w/ non-Optane NVMes"

vars/packageBuildingPipelineDAOS.groovy, vars/rpmlintMockResults.groovy
This should be used very rarely and only in certain circumstances.
=> Allow projects to have rpmlint errors

vars/packageBuildingPipeline.groovy, vars/packageBuildingPipelineDAOS.groovy, vars/rpmlintMockResults.groovy
Remove skipping some build stages on Quick-build.
Fix Groovy linting errors.
=> Refactor rpmlinting of RPMs

vars/testsInStage.groovy
If not then call launch.py --list instead.
=> DAOS-10029 test: Only call list_tests.py if it exists.

vars/daosRepos.groovy, vars/packageBuildingPipelineDAOSTest.groovy, vars/prRepos.groovy
That runs a daos pipeline for all active branches with the new package.
=> Add packageBuildingPipelineDAOSTest()

vars/sconsBuild.groovy, vars/unitPackages.groovy
Add support for el-8 Unit tests.
=> SRE-97 Build: Add support for el-8 unit tests

Jenkinsfile, vars/buildRpm.groovy, vars/buildRpmPost.groovy, vars/rpmlintMockResults.groovy
Reverts daos-stack/pipeline-lib#336
=> Revert "DAOS-11524 build: rpmlint resulting RPMs"

Jenkinsfile, vars/buildRpm.groovy, vars/buildRpmPost.groovy, vars/daosPackagesVersion.groovy, vars/rpmlintMockResults.groovy
Skip rpmlinting for DEB files.
TODO: support lintianing them.
Handle Jenkinsfile Library change to single quote.
=> DAOS-11524 build: rpmlint resulting RPMs

Jenkinsfile, vars/skipStage.groovy, vars/testsInStage.groovy
Fix skip test to account for that.
=> Leap 15 is only run on PRs, not landings

Jenkinsfile, vars/prRepos.groovy, vars/runTest.groovy, vars/skipStage.groovy
=> Let Jenkinsfile decide when stages are run

vars/testBranchRE.groovy
Updating the regular expression to fix indetifying branches run on a weekly cadence.
Signed-off-by: Phil Henderson <phillip.henderson@intel.com>
=> SRE-645 test: Fix detecting 'weekly' branches

Jenkinsfile, vars/skipStage.groovy
Enable malware scanning by default
Signed-off-by: John E. Malmberg <john.e.malmberg@intel.com>
=> SRE-1682 Build: Enable malware scanning

vars/distroVersion.groovy, vars/parseStageInfo.groovy
So that when we change the distro  version supported for a branch we
don't have to do it multiple places.
=> DAOS-12737: centralize the branch->distro mapping

vars/archiveArtifacts.groovy, vars/checkJunitFiles.groovy, vars/functionalTestPostV2.groovy, vars/junit.groovy, vars/junitSimpleReport.groovy, vars/parseStageInfo.groovy, vars/publishValgrind.groovy, vars/runTest.groovy, vars/skipStage.groovy, vars/stepResult.groovy, vars/unitTest.groovy, vars/unitTestPost.groovy
Check for Valgrind errors after running a Unit test.
=> SRE-1729 Build: Fail Unit Test on Valgrind errors

vars/unitTest.groovy, vars/unitTestPost.groovy
Archive NLT valgrind data.
Use stage name for archive file name.
=> DAOS-13490 Build: Archive NLT valgrind data

vars/packageBuildingPipelineDAOSTest.groovy
When doing downstream testing.
=> Fix DAOS version determination

vars/functionalTest.groovy, vars/functionalTestPostV2.groovy
Continue to run the stage if there are errors encountered running launchable.
=> DAOS-13913 test: Ignore launchable errors in test stage

Jenkinsfile, vars/skipStage.groovy
Allow the commit pragmas or build with parameter checkboxes to enable running the Functional Hardware Medium UCX Provider stage in a PR.
=> DAOS-13329 test: Enable running ucx provider testing in PR

Jenkinsfile, vars/publishToRepository.groovy, vars/skipStage.groovy, vars/storagePrepTest.groovy
Make publishToRepositorySystem() convert distro.
Linting fixes.
=> Skip EL9 temporarily

Jenkinsfile
Update the expected results for the skipStage.groovy unit tests to reflect the behavior in landing PRs.
=> DAOS-13934 test: Fix skipStage unit tests for landing PRs.

vars/testsInStage.groovy
When running a PR and no tests were found that match the specified tags list the tests and their tags to assist in debugging newly added tests.
=> DAOS-13882 test: List tests in PR that don't match tags

vars/buildAgentControl.groovy, vars/functionalTest.groovy, vars/functionalTestPostV2.groovy, vars/runTestFunctionalV2.groovy
Take the cluster offline if a hardware failure is discovered on a functional test run.
=> SRE-574 Build: Cluster offline on failure

vars/getFunctionalTestStage.groovy
Add support for running tests from a different branch.
=> DAOS-14658 ci: Add support for running tests from alternate branch

Jenkinsfile, ci/provisioning/post_provision_config.sh, ci/provisioning/post_provision_config_common_functions.sh, ci/provisioning/post_provision_config_nodes.sh, vars/distroVersion.groovy, vars/dockerBuildArgs.groovy, vars/packageBuildingPipelineDAOSTest.groovy, vars/parseStageInfo.groovy, vars/skipStage.groovy, vars/testRpm.groovy
Add support for Leap 15.5 and EL 8.8
Remove 2.2 from the test matrix.
=> Add support for Leap 15.5 and EL 8.8

Jenkinsfile, vars/distroVersion.groovy, vars/getPriority.groovy, vars/packageBuildingPipelineDAOS.groovy, vars/packageBuildingPipelineDAOSTest.groovy
Remove release/2.2 testing in packageBuildingPiplineDAOS*().
Use a variable for the Leap 15 version.
=> Support EL 8.8 and Leap 15.5 for release/2.4

vars/unitPackages.groovy
Description: update unitPackages.groovy for bullseye unit-test
Required-githooks: true
Signed-off-by: Ding Ho ding-hwa.ho@intel.com
=> DAOS-15116 test: fix missing test.cov file and unit-test

src/com/intel/checkoutScmInternal.groovy, vars/getFunctionalTestStage.groovy
Implementing a git remote prune as part of the git checkout
process as defined in https://github.com/jenkinsci/git-plugin
=> SRE-2077 ci: Add git remote prune to checkout.

Jenkinsfile, vars/getFunctionalTags.groovy
Support both Test-tag and Features pragmas by always looking for Features and appending to the Test-tag
=> DAOS-15232 ci: support Test-tag and Features pragmas together

Jenkinsfile, vars/envToPragmas.groovy, vars/getFunctionalTags.groovy, vars/getFunctionalTestStage.groovy, vars/getSkippedTests.groovy, vars/selfUnitTest.groovy
Also, add error check for base_branch.
=> Add general support for Skip-list* tags

Jenkinsfile, vars/distroVersion.groovy, vars/packageBuildingPipelineDAOS.groovy, vars/packageBuildingPipelineDAOSTest.groovy
Testing release/2.6 with EL 8.8 and Leap 15.5.
=> DAOS-15859 test: Adding support for release/2.6

Jenkinsfile, vars/docOnlyChange.groovy, vars/packageBuildingPipeline.groovy, vars/packageBuildingPipelineDAOS.groovy, vars/packageBuildingPipelineDAOSTest.groovy, vars/skipStage.groovy
=> SRE-2453: skip all builds and tests for doc-only PR and unify Build DEB Ubuntu stage names

vars/functionalTest.groovy
Correctly use a default if image_version is not provided to functionalTest.
=> DAOS-16500 test: Fix default image_version

vars/getFunctionalTestStage.groovy, vars/skipFunctionalTestStage.groovy
Fix using pipeline parameters when determining if a Functional Hardware stage should be run.
=> DAOS-17537 test: Fix functional hw param behavior

vars/unitTestPost.groovy
recordIssues expect scm value otherwise it uses random repository (as multiply SCM are used in job)
=> SRE-3029 ci: NLT tests failure in recordIssues

src/com/intel/checkoutScmInternal.groovy, vars/getFunctionalTestStage.groovy
vars/getFunctionalTestStage.groovy:
Functional tests do not use submodules, so do not explicitly check
them out.
=> SRE-3246 No submodules for Functional Tests

vars/buildRpmPost.groovy
Directory was correct on check but wrong for upload
Change-Id: If85959d897e79418dc14e8559c20e41908a3056d
=> DAOS-17472 build: Fix typo
