daos-stack/pipeline-lib

src/com/intel/checkoutScmInternal.groovy
vars/checkPatch.groovy
vars/checkoutScm.groovy
vars/sconsBuild.groovy

Add simplified scm step that allows optional parameters of:
* scm: SCM name, defaults to 'GitSCM'.
* url: Url for Git repository.  If not specified,
*  defaults will be used from the scm global variable.
* cleanAfterCheckout: True for clean after checkout.
* checkoutDir: Optional directory to checkout into.
* branch: Optional branch to checkout, defaults to master.
* withSubmodules: Optional checkout submodules if true.
* credentialsId: Optional credentials ID.

CORCI-504 Add checkoutScm step.

---

vars/sconsBuild.groovy

The test for `env.DAOS_JENKINS_NOTIFY_STATUS` at the job end was inverted.

Invert env.DAOS_JENKINS_NOTIFY_STATUS test at end

---

vars/checkPatch.groovy
vars/sconsBuild.groovy
vars/stepResult.groovy

CORCI-531 Fix pipeline-lib vars/ for local variables
We have come to discover that variables in pipeline-lib's /vars need
to be declared in order to be local.

CORCI-531 Fix pipeline-lib vars/ for local variables

---

vars/runTest.groovy

By calling error() when the result != SUCCESS.

Don't overwrite the test's UNSTABLE/FAILED result

---

vars/sconsBuild.groovy

Expect that the caller (Jenkinsfile) will make the config.log
available as an artifact.

Don't display config.log on scons failure

---

vars/checkPatch.groovy

It would be useful in testing  code_review changes to allow the checkPatch
caller to specify a branch to check out.

CORCI-603 Allow checkPatch caller to specify code_review branch

---

vars/runTest.groovy
vars/sconsBuild.groovy

When a build or test job fails.
Requires the build/test job to inform of the artifact to add the link to.

CORCI-522 Add a link to the log pointing at an artifact

---

vars/provisionNodes.groovy

libipmctl is being installed on the provisioned test nodes by
chef, so we don't need to install it in provisionNodes also.

DCO-8578 Remove installing of libipmctl

---

vars/provisionNodes.groovy

python34-3.4.9-3.el7.x86_64 seems to have removed the
python3 -> python3.4 symlink that existed previous to it.  This is
breaking our usages of python3.
Create the symlink if it doesn't exist.

CORCI-640 Create python3 symlink

---

vars/provisionNodes.groovy

python34-pip-8.1.2-8.el7.noarch.rpm seems to have removed the
pip3 -> pip3.4 symlink that existed previous to it.  This is
breaking our usages of pip3.
Create the symlink if it doesn't exist.

CORCI-640 Create pip3 symlink (#37)

---

vars/runTest.groovy
vars/stepResult.groovy

For GitHub test stages that produce junit output, if the result is not a
failure (i.e. the tests even failed to run) the Detail link should point
to the Jenkins job's test result.

CORCI-644 GitHub status for junit tests should point to the result

---

vars/sconsBuild.groovy

No point in doing another checkout of what was already checked out.

CORCI-660 Only do a checktouScm() if an scm parameter was defined

---

vars/sconsBuild.groovy

This reverts commit a1e110a5afdb97efda2a4c490a69d9863b3921ca.
The checkoutScm() is always needed to get the submodules.
Will need to achieve CORCI-660's goal without removing the checkout.

Revert "CORCI-660 Only do a checkoutScm() if an scm parameter was defined (#43)"

---

vars/sconsBuild.groovy

Issues as that tee_file isn't always set so if scons build failed, it would get interpreted as a log failure but PIPESTATUS[1] would be empty to the build would happily pass.
Adding | true as default setting for "tee_file" fixes the
issue.

CORCI-663 build: Don't ignore scons build error 

---

vars/sconsBuild.groovy

As true seems to cause it's stdin producer to have issues as well as it
consumes it's stdin which wee don't really want to do.

CORCI-663 build: use cat instead of true

---

vars/provisionNodes.groovy

It was only ever needed for Avocodo's expect module but we don't
use that any more.

CORCI-675 Remove python2-aexpect from post provision install

---

vars/runTest.groovy

This is what signals the pipeline to not continue beyond the run_test.sh
state if it fails for example.

Post an error to the job if runTest stage fails

---

vars/stepResult.groovy

Now that we have changed the Details link on GitHub commit status to
point at the console log for the stage, update the comments to point
to the same link instead of Blue Ocean.

CORCI-619 Make the link in comment e-mails point to the Details link

---

vars/provisionNodes.groovy

ProvisionNodes needs to be able to be called multiple times in a step.
The Jenkins account being added to the CI nodes may already exist.
Need to sync the file system after provisioning to make sure data
persists after a power cycle.

CORCI-539 build: provisionNodes fix

---

vars/sconsBuild.groovy

We recently removed the _m from the config file so the cleanup
needs to remove the new file instead.

DAOS-623 build: Fix the filename from daos_m to daos

---

Jenkinsfile
docker/Dockerfile.centos.7
vars/daosStackNotifyStatus.groovy
vars/publishToRepository.groovy

Add a publishToRepository step to the public pipeline-lib as a wrapper
for an optional system provided step that handles the actual repository
operations.  This will eventually allow other Jenkins systems to use
our jenkinsfiles and pipeline-lib repository.

CORCI-734 build: Add publishToRepository step

---

Jenkinsfile

Adding a test is a two step procedure requiring changing the Jenkinsfile
@Library statement to match the pull request branch until after the
change is landed, and then a second pull request to set the Jenkinsfile
to back to using master for this library.

CORCI build: Set @Library to master

---

vars/stepResult.groovy

The landings to a branch don't show a completion status in github unless
travis reports an error.
This is because the code to report completion commit statuses in github
is only operating on PRs.

CORCI-776 build Update github when stages complete on branches

---

vars/runTest.groovy

When the junit files are missing, the `grep` of them (for errors and failures) returns a false negative result.  This results in the test being considered a pass when junit results even failed to be produced.
So make sure there are junit files to process before accepting the return status of `grep` on them since `grep` return status on them is the same when they are missing and when they contain no errors or failures.

Don't try to grep missing files

---

vars/packageBuildingPipeline.groovy

Allows a `Jenkinsfile` to simply call:
```
packageBuildingPipeline()
```
to build on all supported distros but allows projects to only build on a subset of distros if desired.

Support defaults for package name and distros

---

vars/packageBuildingPipeline.groovy

Ubuntu pbuilder does not put the original tarball into its results
directory if the Ubuntu patch revision is not 0 or 1, as there are no
changes to the tarball previously uploaded to their repository.

CORCI-784 build: Ubuntu Packaging updates

---

vars/packageBuildingPipeline.groovy

vars/packageBuildingPipeline.groovy:
The Slurm and Meson pckages currently do not pass lint.
This allows a Jenkinsfile to supresss the lint checks.

CORCI-786 build: Allow rpmlint checks to fail.

---

vars/packageBuildingPipeline.groovy
vars/provisionNodes.groovy

Fix collection of CentOS 7 mock rpm build failures.

CORCI-788 build: Fix collection of rpm failures

---

vars/provisionNodes.groovy

Skip restoring a snapshot if the only system in the request
for a snapshot restore is not a VM.

CORCI-792 build: Skip snapshot for non-VM

---

Jenkinsfile
vars/packageBuildingPipeline.groovy

The OBS build tool has depdency resolution limitations that make it
unable to build some packages. In particular it only recognizes a
single verison of a given package and so is quite unable to handle
our multi-package-version repos.
Since we are using mock for all RPM builds, we might as well just use
Fedora as the build platform to get much more recent versions of mock.
Signed-off-by: Brian J. Murrell brian.murrell@intel.com

Abandon the OBS build tool and use mock instead

---

vars/provisionNodes.groovy

Allow CI to ssh access to the root account of CI nodes.

DCO-8879 build: Fixup SSH access.

---

vars/packageBuildingPipeline.groovy

Update packageBuildingPipeline.groovy for CentOS 8 and
retire SLES-12/Leap-42 for default builds.

DCO-8741 build: Add CentOS 8 part 2

---

vars/packageBuildingPipelineDAOS.groovy

File: vars/packageBuildingPipelineDAOS.groovy
When boot-strapping a new Jenkins the test stage can fail when not all
the RPMs are present.
Ignore test failures caused by missing packages.

CORCI-819 build: Allow bootstrap of RPMs

---

vars/packageBuildingPipeline.groovy
vars/packageBuildingPipelineDAOS.groovy

For build post-mortem, even when the build succeeds.

Collect config.logs on successful runs also

---

vars/stepResult.groovy

Since we have branch names with / in them, when building a URL with
a branch name in it, we must escape the /s.

Escape slashes when building URLs

---

Jenkinsfile
vars/provisionNodes.groovy

Add CI profile support for el7 and sles15, opensuse15.
Remove SLES-12 support from provisionNodes.

CORCI-768 build: Add CI profile support

---

vars/provisionNodes.groovy

It needs to be escaped to _ since filenames cannot have / in them.

Fix repo file name when branch has a / in it

---

Jenkinsfile
vars/provisionNodes.groovy

Matrix parameters which need to be passed to node provisioning
are strings, so need to be used as int.

CORCI-887 build: Matrix parameters are strings

---

vars/provisionNodes.groovy

DAOS depends on it so no need to install it explicitly.

Don't install fuse in post-provisioning

---

vars/sconsBuild.groovy

In order to customize builds, we need new options for builder:
BUILD_ROOT, BUILD_TYPE, WARNING_LEVEL
Also added COMPILER comment

DAOS-623 build: Add new scons options to scons builder

---

src/com/intel/checkoutScmInternal.groovy
vars/checkPatch.groovy

scm.branches contains a branch name, not a commit.  That means that
on Replay, where you want to re-build an older build, scm will build
the branch tip, not the commit being Replayed.
Also in the case quick successive commits to a branch, again since
scm.branches contains the branch name, by the time the first of some
successive commits gets to the point of doing the checkout, the branch
tip might be a newer commit than that being built, in which case the
build ends up bulding a subsequent commit, not the one it should be.
Use $GIT_COMMIT to resolve this issue, as it should always point at
the specific commmit, no the branch tip.

CORCI-922 build: Use $GIT_COMMIT as the default object to check out

---

vars/packageBuildingPipeline.groovy
vars/packageBuildingPipelineDAOS.groovy

To Build Log to make it more clear that that's where the
build log can be viewed.

Change Collect Artifacts step name

---

vars/publishToRepository.groovy

We have repos that want to publish from other than the doas known
publishing branches.

Resurrect publish_branch option

---

vars/runTestFunctional.groovy

So that shutdowns, etc. don't get hung up on the NFS mount.

Unmount NFS share at test exit

---

.github/workflows/update_pipeline_lib_branch.yml
Jenkinsfile

Add pipeline-lib branch update action

---

vars/valgrindReportPublish.groovy

The stage for it might have been skipped.
Future enhancement is to tell valgrindReportPublish which stages were
run so that it can produce an error if a stash for a run stage was
missing.

Ignore a failure to unstash a valgrind stash

---

vars/runTest.groovy

Change runTest() to propagate errors so that they stop the build from
advancing onto the next stage.

CORCI-1011 unit-test: Abort the build on test failure/unstable result

---

vars/archiveArtifacts.groovy
vars/junit.groovy
vars/publishValgrind.groovy
vars/runTest.groovy

This will prevent the dreaded "...[truncated 135494 chars]..." in the
middle of hte Standard Output section of displayed JUnit result.  It
should then also result in full wrapping instead of the portion after
the truncation displaying the \n literally.
Also fix up the lack of $NO_CI_TESTING interpolation due to it being
inside single quotes.
Convert the use of def to specific primatives/types.

Don't truncate std{out,err} in JUnit results

---

vars/archiveArtifacts.groovy
vars/junit.groovy
vars/publishValgrind.groovy
vars/runTest.groovy

This reverts portions of commit 5162a9c
that converted defs to types and primitives as that was causing:
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object '[]' with class 'java.util.ArrayList' to class 'java.util.Map' due to: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: java.util.Map()

￼Revert some of "Don't truncate std{out,err} in JUnit results (#172)" 

---

vars/unitTestPost.groovy

This was allowed due to race conditions in the code but they're fixed
so remove the provision for this.
Tidy up some legacy code that's not required any more.

CORCI-1032 nlt: Do not ignore LOW severity regressions.

---

vars/parseStageInfo.groovy

Limit the tests added by Features: tags to tests that we normally run
in one of our existing test buckets.
Skip-PR-comments: true

Only run runnable tests in Features: pragma

---

vars/functionalTest.groovy
vars/parseStageInfo.groovy

To test.  Otherwise fall back to existing behaviour for backward
compatibility.
Skip-PR-comments: true

Allow functionalTest caller to specify the tag

---

vars/parseStageInfo.groovy

In working on the last patch, it was missed that subsequent to the
config['test_tag'] processing and combining with the cluster size
restricting tags, into result['test_tag'], a subsequent override of the
result['test_tag'] with the bare config['test_tag'] was being done.
Remove that.

Followup to previous patch to remove later override

---

vars/parseStageInfo.groovy

So that Test-tag: can be used to set tags for all functional stages with
a single pragma.
Skip-PR-comments: true

Rename Test-tag: -> Test-tag-vm:

---

Jenkinsfile
vars/provisionNodesV1.groovy

Copy the scripts from the daos-stack project as a start so that
the provisionNodes tests are now testing the same as Daos

CORCI-1046 Change to test new provision nodes

---

vars/functionalTest.groovy
vars/functionalTestPost.groovy
vars/functionalTestPostV2.groovy
vars/runTestFunctional.groovy
vars/runTestFunctionalV1.groovy
vars/runTestFunctionalV2.groovy

"DAOS-6274 test: Restructure DAOS logs #184" broke the pipeline-lib API
without providing any backward compatibliity.
This fixes that breakage.

Fix API breakage

---

vars/dockerBuildArgs.groovy

This allows periodic rebuild as well as per-build refreshes, the
benefit of which is to keep the refresh time from increasing over
time as the base images age.

DAOS-6742 build: Add CB0 to CACHEBUST option to allow multi-stage.

---

vars/parseStageInfo.groovy

As in "", rather that starting out null and subsequently being appended
to.

Ensure that result['test_tag'] starts out empty

---

vars/dockerBuildArgs.groovy
vars/functionalPackages.groovy
vars/getDAOSPackages.groovy
vars/hwDistroTarget.groovy
vars/parseStageInfo.groovy
vars/provisionNodes.groovy
vars/rpmTestVersion.groovy
vars/scanRpms.groovy
vars/skipStage.groovy
vars/storagePrepTest.groovy
vars/testRpm.groovy
vars/unitTest.groovy

Separate out a 'ci_target' from a build 'target' to allow more easily
running tests on newer pre-built CI images.
dockerBuildArgs.groovy:
Add CentOS 8 special app stream repo
Fix missing variable declaration
parseStageInfo.groovy
Set the 'ci_target' member for node provisioning
functionalTest.groovy:
scanRpms.groovy:
testRpm.groovy:
unitTest.groovy
Now use 'ci_target' for node provisioning
provisionNodes.groovy:
Fix some declarations to be more specific types
Remove some dead code

CORCI-1074 build: Allow special CI targets

---

Jenkinsfile
vars/cachedCommitPragma.groovy
vars/getPriority.groovy
vars/skipStage.groovy
vars/testsInStage.groovy

Change PRs to only run CentOS7 on VMs.
Landings and timed builds are moved down to the same priority as PRs.
Run build and test stages on an empty commit message with PR-repos* set.
Because there are no code changes, these commits will pass the doc-only
test and not run build and test, but the PR-repos* pragmas tell us that
this is a commit being used to test updates to a dependency build.
Skip UT stage on Quick-build (which is implied with Quick-Functional).

CORCI-1081 ci: Changes to increase CI throughput

---

vars/packageBuildingPipeline.groovy
vars/packageBuildingPipelineDAOS.groovy

Add CentOS 8.4 and Leap 15.3 as additional build targets while
keeping the CentOS 8.3 and Leap 15.2 buids.
Add test CentOS 8 build for testing.

CORCI-1103 Build: Add CentOS 8.4, leap 15.3

---

vars/skipStage.groovy

Until the Internet I/O operations of it can be made more reliable.

Skip RPM scanning stages by default

---

vars/functionalTest.groovy
vars/functionalTestPostV2.groovy

/ (or even the URL encoding of it) is not legal in a Launchable build name.

Replace %2F in Launchable's build name with -

---

vars/sconsFaultsArgs.groovy

This is just a hack to be able to enable fault injection until we have a
build parameter dedicated to this.

Build a dev build if the test tag has "with_fi" in it

---

vars/getDAOSPackages.groovy

Ensure the same version of the daos-serialize RPM that was built in the
PR is installed during testing.

DAOS-623: Install matching version of daos-serialize

---

vars/dockerBuildArgs.groovy
vars/sconsBuild.groovy
vars/skipStage.groovy

Add a Skip-build-centos7-gcc pragma, and enable parallel_build option
for docker builds.

CART-89 build: Add a skip-pragma for CentOS 7 builds.

---

vars/parseStageInfo.groovy

To support newer clusters in CI update the default launch.py --nvme
argument for HW clusters.

DAOS-9562 test: Support VMD clusters w/ non-Optane NVMes

---

Jenkinsfile
vars/parseStageInfo.groovy

All HW Medium clusters have dual IB, so the ib2 tag is not needed.
Signed-off-by: Dalton Bohning <dalton.bohning@intel.com>

DAOS-9090: remove ib2 tag

---

vars/skipStage.groovy

The 'Functional on * with Valgrind' stage is now skipped by default and
requires a 'Skip-func-test-vm-valgrind: false' commit pragma to enable
running the stage.

DAOS-10585 test: Disable runnig Functional * w/ Valgrind stage

---

vars/skipStage.groovy

Only run the the Functional on * with Valgrind test stage if the
Skip-func-test-vm-valgrind pragma is set to false.  All other
conditionals that previously determined if the stage was skipped have
been removed.

DAOS-10585 test: Always skip the w/ Valgrind stage

---

vars/parseStageInfo.groovy

Do not allow commit pragmas left in landing PRs to influence which tests
are run in daily builds.

DAOS-10645 ci: Ensure consistent testing in timer CI runs

---

vars/functionalTest.groovy
vars/parseStageInfo.groovy

Enable installing the mercury-ucx RPM whenever the ucx provider is
specified for functional testing.  This will cover cases where the ucx
provider is specified through commit pragmas in any branch.

DAOS-9979 ci: Enable regular weekly ucx testing

---

vars/testsInStage.groovy

Daily PRs do not have CHANGE_TARGET defined, so verify the value is set
before checking its value.

DAOS-9989 test: Fix Cannot invoke method startsWith() on null object

---

vars/daosPackagesVersion.groovy

We have switched to EL8 for most builds, so reference EL8
instead of EL7 to determine the latest DAOS RPMs.
Signed-off-by: Dalton Bohning <dalton.bohning@intel.com>

DAOS-10847 pipeline: Reference EL8 for latest DAOS RPMs

---

ci/provisioning/post_provision_config_common_functions.sh
vars/daosPackagesVersion.groovy
vars/daosRepos.groovy
vars/parseStageInfo.groovy
vars/skipStage.groovy
vars/testsInStage.groovy

Enable weekly tcp/ucx testing in new provider-testing* branches.  Remove
references to the no longer used Functional Hardware * TCP/UCX test
stages.

DAOS-9989 test: Enable provider-testing* branches

---

ci/provisioning/post_provision_config.sh
vars/dockerBuildArgs.groovy

This reverts commit 62bc371d9c568cab1aaa4dadb3e755ad993c1bce.
CACHEBUST was always intended to be an absolute cache buster.  It was
not meant to represent tasks that were subsequently decided should be
done weekly instead of done always.  CB0 is in fact exactly that -- a
weekly cache buster and should have been used where CACHEBUST was
repurposed to be weekly.
There are, and always will be tasks which we want to happen on every
Docker build.  These are forced with CACHEBUST.

Revert "DAOS-623 build: Update docker cachebust to be weekly. (#292)"

---

Jenkinsfile

We have lots of different paths based on whether something is a landing
(i.e. branch name is master, etc.) or not and need to account for that
logic in landings to this branch.

More fixing skip pragma tests on PR landings

---

Jenkinsfile
vars/checkJunitFiles.groovy

Junit failures can be "<failure " or "<failure>".

SRE-519 Build: Fix junit failure lookup

---

Jenkinsfile
vars/packageBuildingPipelineDAOSTest.groovy

Update pipeline-lib dependency building stages to remove the no longer used Functional Hardware Small stage.
Signed-off-by: Phil Henderson <phillip.henderson@intel.com>

DAOS-12064 test: Remove HW Small stage from pipeline-lib testing

---

vars/dockerBuildArgs.groovy
vars/valgrindReportPublish.groovy

Reverts daos-stack/pipeline-lib#352
Needs a daos repo update to bridge the switch from ${REPO_URL}${REPO_UBUNTU_20_04}
to  ${REPO_FILE_URL%repo-files/}daos-stack-daos-ubuntu-20.04-x86_64-stable-local.

Revert "Set BASE_DISTRO for Leap 15"

---

vars/parseStageInfo.groovy
vars/skipStage.groovy

Add support for the Functional Hardware Medium TCP Provider stage in order to run any 'provider' tagged tests in the tcp provider branches.
Signed-off-by: Phil Henderson <phillip.henderson@intel.com>

DAOS-12021 test: Add support for HW Medium TCP Provider stage

---

vars/skipStage.groovy

Remove ‘Functional Hardware Medium UCX Provider' stage for PRs but keep it for daily runs.
Modifyng 'vars/skipStage.groovy' in pipeline-lib.
Signed-off-by: Saurabh Tandan <saurabh.tandan@intel.com>

DAOS-12562 test: Remove 'Functional Hardware Medium UCX Provider' stage for PRs

---

vars/publishToRepository.groovy

Include publishing RPMs to artifactory from testbuild branches.

DAOS-12441 test: Publish RPMs from testbuild branches

---

vars/parseStageInfo.groovy

Moving setting the default Test-Nvme argument in pipeline-lib as opposed to in the Jenkinsfile.

DAOS-11421 test: Set the default Test-nvme arg for vos_on_blob

---

vars/stepResult.groovy

Test results have a optional class name  which defaults
to (root) however the Github comments on test failures link
to this default class.  This means that for tests which define
a class but fail the link can either be invalid or point to
other, un-related tests which might not have failed.

DAOS-623 test: Fix link to Jenkins test results.

---

Jenkinsfile
vars/daosPackagesVersion.groovy
vars/packageBuildingPipelineDAOSTest.groovy
vars/rpmDistValue.groovy
vars/skipStage.groovy
vars/testBranchRE.groovy

Add daosLatestVersion() tests.
Use el8 as the distro to find latest packages in
packageBuildingPipelineDAOSTest().
Add rpmDistValue() variable.
Disable EL9 running on PRs by default.

Add daosPackagesVersion() tests

---

Jenkinsfile
vars/functionalTest.groovy
vars/getFunctionalArgs.groovy
vars/getFunctionalNvme.groovy
vars/getFunctionalProvider.groovy
vars/getFunctionalRepeat.groovy
vars/getFunctionalStageTags.groovy
vars/getFunctionalTags.groovy
vars/getPragmaSuffix.groovy
vars/parseStageInfo.groovy
vars/runTestFunctionalV2.groovy
vars/skipStage.groovy
vars/testsInStage.groovy

Provide additional flexibility for passing launch.py tag, provider, and nvme argument values on a per stage and per branch basis.  Existing branch Jenkinsfile implementations will use the existing behavior.

DAOS-13934 test: Support passing launch.py args per stage

---

Jenkinsfile

Fix the unit test for landing prs.
Skip-daos-build-and-test: true

DAOS-13529 test: Fix skipFunctionalTestStage unit test 1

---

vars/functionalTestPostV2.groovy

If any test error occurs in a functional test, make sure that the stage is set to unstable, not error, so that it does cause other testing to be aborted.
This will not change a stage from an error state to an unstable state.

SRE-1981 Build: Set unstable on test error

---

vars/skipStage.groovy

Includes a workaround to skip the 'Test RPMs on Leap 15.4' stage if the CI_RPM_TEST_VERSION build parameter is specified.

SRE-1993 test: Enable skip logic for new Test RPMs stages

---

Jenkinsfile
vars/getPriority.groovy
vars/pragmasToEnv.groovy

When performing downstream testing, take any "Test-tag:" pragma from the pipeline-lib PR and pass it to the downstream test jobs.

Allow specifying downstream Test-tag value

---

Jenkinsfile
vars/getFunctionalStageTags.groovy

All VM tests in master and 2.4 are tagged with "vm", so you "vm" instead of "-hw".

SRE-1975 test: replace -hw with vm

---

vars/jobStatusUpdate.groovy
vars/runTest.groovy

Added to the map that runTest returns. Also fix for jobStatusUpdate. It was previously overwriting the map each time.
Signed-off-by: Ryon Jensen <ryon.jensen@intel.com>

SRE-2082 ci: Add more timing info to jenkins_result file

---

vars/unitTestPost.groovy

The ignoreFailedBuilds parameter was removed in reaction to the warnings-ng plug api change. Adding the requiredResult parameter to the discoverGitReferenceBuild call should create the same behavior.
Doc-only: false

SRE-2145 ci: Add requiredResult

---

vars/getFunctionalTestStage.groovy

Allow defing a UCX test stage with getFunctionalTestStage that will be provisioned correctly w/o the need for a specific stage name format.

DAOS-15772 test: Support provider independence from stage name

---

Jenkinsfile
vars/buildDaosJob.groovy

Add the buildDaosJob routine to simplify projects doing downstream build of DAOS in order to validate changes.

SRE-2248 Add buildDaosJob routine

---

Jenkinsfile
vars/docOnlyChange.groovy

Empty commit shall not be treated as `Doc-only: true`
Fix the problem introduced by https://github.com/daos-stack/pipeline-lib/pull/444:
https://build.hpdd.intel.com/job/daos-stack/job/daos/job/daily-2.6-testing/114/console
```
14:00:27  + TARGET_BRANCH=daily-2.6-testing
14:00:27  + set -uex
14:00:27  + git fetch origin daily-2.6-testing
14:00:27  From https://github.com/daos-stack/daos
14:00:27   * branch                daily-2.6-testing -> FETCH_HEAD
14:00:27  + git diff --no-commit-id --name-only origin/daily-2.6-testing HEAD
14:00:27  + grep -v -e '^docs/' -e '\.md$' -e '^.*LICENSE.*$'
14:00:27  Stage "Test" skipped due to when conditional
```

SRE-2507 common: do not report "Doc-only: true" for empty commit

---

vars/branchTypeRE.groovy
vars/skipStage.groovy
vars/startedByLanding.groovy

Treat landing builds on feature branches the same as master. Treat skipping unstable builds on feature branches the same as master.

DAOS-16683 test: Add support for feature branches

---

vars/packageBuildingPipelineDAOSTest.groovy

Propagate the value of the `Allow-unstable-test` commit pragma to the `CI_ALLOW_UNSTABLE_TEST` parameter of package downstream build.

SRE-2736: propagate Allow-unstable-test to CI_ALLOW_UNSTABLE_TEST

---

ci/provisioning/post_provision_config_common.sh
ci/provisioning/post_provision_config_nodes_EL_8.sh
vars/stepResult.groovy

Get rid of the tight connection to the hpdd.intel.com artifactory. Instead, use a generic address: `https://artifactory/`

SRE-2772 ci: get rid of link to hpdd artifactory

---

vars/unitTestPost.groovy

NLT results analysis reports an error when it can not get source code of the reported warning.
PMDK reports warnings/errors via VOS logging system but the source code is not available.
Static analysis of NLT results does not work properly when
a warning source code is out of scope of the project.
An error is reported in such case and  the whole stage status
is changed to FAILURE.
```
[NLT results] [-ERROR-] Can't create fingerprints for some files:
[NLT results] [-ERROR-] - 'pmdk/.../src/common/set.c' file not found
...
[NLT results] Failing build because analysis result contains errors
```
To prevent this problem, all PMDK-related messages are filtered out.
NLT results Warnings section will include warnings but will not
provide any detail information about location of this warning
in the …

DAOS-16661 ci: Ignore detail analysis of PMDK warnings in NLT

---

vars/rpmlintMockResults.groovy

rpmlintMockResults.groovy was screen scraping the results of rpmlint 
to get additional information. With an updated to rpmlint, this broke.
Simplifying the script to just use rpmlint return code.

SRE-2920 ci: Simplify RPM Lint

---

vars/distroVersion.groovy
vars/docOnlyChange.groovy
vars/getFunctionalTestStage.groovy
vars/notifyBrokenBranch.groovy
vars/packageBuildingPipeline.groovy
vars/parseStageInfo.groovy
vars/provisionNodes.groovy
vars/sconsBuild.groovy
vars/skipStage.groovy
vars/unitTest.groovy

vars/notifyBrokenBranch.grooy:
This routine was doing a lookup of the enviroment Map which is not
allowed in the pipeline-lib sandboxed operation.

SRE-2932 Fix notifyBrokenBranch

---

Jenkinsfile
vars/buildRpm.groovy
vars/dockerBuildArgs.groovy
vars/functionalTest.groovy
vars/functionalTestPostV2.groovy
vars/packageBuildingPipeline.groovy
vars/packageBuildingPipelineDAOS.groovy
vars/packageBuildingPipelineDAOSTest.groovy
vars/provisionNodes.groovy

The `HTTPS_PROXY` variable set in Jenkins may force any shell script to use a proxy server.
This is not expected, as we want to avoid using a proxy unless it is explicitly needed by the DAOS tests or the build process.

SRE-3104 ci: Use DAOS specific HTTPS_PROXY variable

---

vars/buildRpmPost.groovy

When building the new style RPMs, we need to publish dependencies to a different repo.
system-pipeline-lib uses the "product" and chooses the repo based on whether daos is in the name
so use this fact to publish dependencies, if built, to the dependency repo.
Change-Id: Iafe3932bbb7f2cfd5c5d2695cece9fa051130391

DAOS-17472 build: Promote rpms to separate repos
